# Instalacion de Librerias

In [1]:
!pip install transformers datasets
!pip install 'transformers[torch]'
!pip install psycopg2-binary

Requirement already satisfied: transformers in /opt/conda/lib/python3.8/site-packages (4.45.2)
Requirement already satisfied: datasets in /opt/conda/lib/python3.8/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.8/site-packages (from transformers) (1.23.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /opt/conda/lib/python3.8/site-packages (from transformers) (0.20.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.8/site-packages (from transformers) (6.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.8/site-packages (from transformers) (21.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /opt/conda/lib/python3.8/site-packages (from transformers) (0.26.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.8/site-packages (from transformers) (2.32.3)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.8/site-packages (from transformers) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.8/site-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.8/site-packages (from transformers) (4.66.5)
Requirement already satisfied: filelock in /opt/conda/lib/python3.8/site-packages (from transformers) (3.16.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/lib/python3.8/site-packages (from datasets) (0.3.8)
Requirement already satisfied: fsspec[http]<=2024.6.1,>=2023.1.0 in /opt/conda/lib/python3.8/site-packages (from datasets) (2024.6.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.8/site-packages (from datasets) (3.5.0)
Requirement already satisfied: pandas in /opt/conda/lib/python3.8/site-packages (from datasets) (1.5.0)
Requirement already satisfied: multiprocess in /opt/conda/lib/python3.8/site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.8/site-packages (from datasets) (3.10.10)
Requirement already satisfied: pyarrow>=15.0.0 in /opt/conda/lib/python3.8/site-packages (from datasets) (17.0.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.8/site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/conda/lib/python3.8/site-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.8/site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.8/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.8/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /opt/conda/lib/python3.8/site-packages (from aiohttp->datasets) (1.15.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.8/site-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.8/site-packages (from requests->transformers) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.8/site-packages (from requests->transformers) (2022.9.24)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.8/site-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.8/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.8/site-packages (from pandas->datasets) (2022.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.8/site-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)
Requirement already satisfied: transformers[torch] in /opt/conda/lib/python3.8/site-packages (4.45.2)
Requirement already satisfied: requests in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (2.32.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (0.26.0)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (0.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (21.3)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (1.23.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (6.0)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (4.66.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (0.20.1)
Requirement already satisfied: filelock in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (3.16.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.8/site-packages (from transformers[torch]) (2024.9.11)
Collecting accelerate>=0.26.0
  Downloading accelerate-1.0.1-py3-none-any.whl (330 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 330.9/330.9 kB 31.0 MB/s eta 0:00:00
Collecting torch
  Downloading torch-2.4.1-cp38-cp38-manylinux1_x86_64.whl (797.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 794.7/797.1 MB 101.3 MB/s eta 0:00:0100:01Requirement already satisfied: psycopg2-binary in /opt/conda/lib/python3.8/site-packages (2.9.10)

# Carga de Librerias

In [2]:
import requests, csv, os ,warnings
import pandas as pd
from datetime import date
import json
import shutil
import requests

In [3]:
warnings.filterwarnings("ignore")

# Creacion del listado de URL para APIREST

In [4]:
urlBase="https://api.jolpi.ca/ergast/f1"

In [5]:
# def get_data_from_api(endpoint, table_key_1, table_key_2):
#     try:
#         response = requests.get(f"{urlBase}/{endpoint}", params={"limit": 1000})
#         # Verifica si la solicitud fue exitosa (código de estado 200)
#         if response.status_code == 200:
#             # Convierte la respuesta JSON en un diccionario
#             data = response.json()
#             data = data['MRData']
#             print(data)
#             # Extrae los datos de la clave específica (e.g., 'DriverTable', 'RaceTable')
#             if table_key_1 in data:
#                 table_data = data[table_key_1][table_key_2]
#                 # Convierte la tabla en un DataFrame de pandas
#                 df = pd.DataFrame(table_data)
#                 print(f"Datos obtenidos de {endpoint} exitosamente.")
#                 return df
#             else:
#                 print(f"La clave '{table_key_1}' no se encontró en la respuesta.")
#                 return pd.DataFrame()  # Retorna un DataFrame vacío si no se encuentra la clave
#         else:
#             print(f"Error {response.status_code} al obtener datos de {endpoint}.")
#             return pd.DataFrame()  # Retorna un DataFrame vacío en caso de error
#     except Exception as e:
#         print(f"Error al conectar con la API: {e}")
#         return pd.DataFrame()

In [7]:
df_race = pd.read_csv("data/structured/races.csv")
# df_drivers = get_data_from_api("drivers", "DriverTable", "Drivers")
df_drivers = pd.read_csv("data/structured/drivers.csv")
# lee el csv data/structured/lap_times.csv
df_laps = pd.read_csv('data/structured/lap_times.csv')
# Muestra un resumen de los DataFrames obtenidos
print("Resumen de la tabla 'race':")
display(df_race)

print("\nResumen de la tabla 'drivers':")
display(df_drivers)

print("\nResumen de la tabla 'laps':")
display(df_laps)

Resumen de la tabla 'race':

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

Resumen de la tabla 'drivers':

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
855,857,piastri,81,PIA,Oscar,Piastri,2001-04-06,Australian,http://en.wikipedia.org/wiki/Oscar_Piastri
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,40,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto

Resumen de la tabla 'laps':

        raceId  driverId  lap  position      time  milliseconds
0          841        20    1         1  1:38.109         98109
1          841        20    2         1  1:33.006         93006
2          841        20    3         1  1:32.713         92713
3          841        20    4         1  1:32.803         92803
4          841        20    5         1  1:32.342         92342
...        ...       ...  ...       ...       ...           ...
582762    1138       855   57        15  1:37.875         97875
582763    1138       855   58        15  1:37.758         97758
582764    1138       855   59        15  1:37.759         97759
582765    1138       855   60        15  1:39.830         99830
582766    1138       855   61        15  1:38.975         98975

[582767 rows x 6 columns]

In [9]:
df_race = df_race.replace('\\N', None)
df_drivers = df_drivers.replace('\\N', None)
# df_drivers = df_drivers.drop(columns=["permanentNumber"])
df_laps = df_laps.replace('\\N', None)


print("Resumen de la tabla 'race':")
display(df_race)

print("\nResumen de la tabla 'drivers':")
display(df_drivers)

print("\nResumen de la tabla 'laps':")
display(df_laps)

Resumen de la tabla 'race':

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,None,None,None,None,None,None,None,None,None,None
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,None,None,None,None,None,None,None,None,None,None
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,None,None,None,None,None,None,None,None,None,None
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,None,None,None,None,None,None,None,None,None,None
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,None,None
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,None,None,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,None,None
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,None,None,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,None,None

Resumen de la tabla 'drivers':

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,None,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,None,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
855,857,piastri,81,PIA,Oscar,Piastri,2001-04-06,Australian,http://en.wikipedia.org/wiki/Oscar_Piastri
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,40,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto

Resumen de la tabla 'laps':

        raceId  driverId  lap  position      time  milliseconds
0          841        20    1         1  1:38.109         98109
1          841        20    2         1  1:33.006         93006
2          841        20    3         1  1:32.713         92713
3          841        20    4         1  1:32.803         92803
4          841        20    5         1  1:32.342         92342
...        ...       ...  ...       ...       ...           ...
582762    1138       855   57        15  1:37.875         97875
582763    1138       855   58        15  1:37.758         97758
582764    1138       855   59        15  1:37.759         97759
582765    1138       855   60        15  1:39.830         99830
582766    1138       855   61        15  1:38.975         98975

[582767 rows x 6 columns]

# Preparo la BD

In [11]:
df_drivers.head(1)

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton

create database metastore_db;

CREATE TABLE Formula1_Drivers (
    driverId INTEGER PRIMARY KEY,
    driverRef TEXT NOT NULL,
    number INTEGER,
    code TEXT,
    forename TEXT NOT NULL,
    surname TEXT NOT NULL,
    dob DATE NOT NULL,
    nationality TEXT NOT NULL,
    url TEXT
);


CREATE TABLE Formula1_Laps (
    raceId INTEGER,
    driverId INTEGER,
    lap INTEGER,
    position INTEGER,
    time TEXT,
    milliseconds INTEGER,
    PRIMARY KEY (raceId, driverId, lap)
);


CREATE TABLE Formula1_Races (
    raceId INTEGER PRIMARY KEY,
    year INTEGER NOT NULL,
    round INTEGER NOT NULL,
    circuitId TEXT NOT NULL,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME,
    url TEXT,
    fp1_date DATE,
    fp1_time TIME,
    fp2_date DATE,
    fp2_time TIME,
    fp3_date DATE,
    fp3_time TIME,
    quali_date DATE,
    quali_time TIME,
    sprint_date DATE,
    sprint_time TIME
);

# Conexion a PosgresDB

In [8]:
import psycopg2
conn = psycopg2.connect(
    dbname='metastore_db',  # Cambia por tu nombre de base de datos
    user='hive',        # Cambia por tu usuario
    password='password',  # Cambia por tu contraseña
    host='hive4-postgres',         # Cambia si es necesario
    port='5432'               # Cambia si es necesario
)

# Creación de tablas

In [9]:

cursor = conn.cursor()

# Consultas para eliminar las tablas si existen
drop_drivers_table = "DROP TABLE IF EXISTS Formula1_Drivers;"
drop_laps_table = "DROP TABLE IF EXISTS Formula1_Laps;"
drop_races_table = "DROP TABLE IF EXISTS Formula1_Races;"

# Ejecutar las consultas para eliminar las tablas
cursor.execute(drop_drivers_table)
cursor.execute(drop_laps_table)
cursor.execute(drop_races_table)

# Consultas para crear las tablas
create_drivers_table = """
CREATE TABLE Formula1_Drivers (
    driverId INTEGER PRIMARY KEY,
    driverRef TEXT NOT NULL,
    number INTEGER,
    code TEXT,
    forename TEXT NOT NULL,
    surname TEXT NOT NULL,
    dob DATE NOT NULL,
    nationality TEXT NOT NULL,
    url TEXT
);
"""

create_laps_table = """
CREATE TABLE IF NOT EXISTS Formula1_Laps (
    raceId INTEGER,
    driverId TEXT,
    lap INTEGER,
    position INTEGER,
    time TEXT,
    milliseconds INTEGER,
    PRIMARY KEY (raceId, driverId, lap)
);
"""

create_races_table = """
CREATE TABLE IF NOT EXISTS Formula1_Races (
    raceId INTEGER PRIMARY KEY,
    year INTEGER NOT NULL,
    round INTEGER NOT NULL,
    circuitId TEXT NOT NULL,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME,
    url TEXT,
    fp1_date DATE,
    fp1_time TIME,
    fp2_date DATE,
    fp2_time TIME,
    fp3_date DATE,
    fp3_time TIME,
    quali_date DATE,
    quali_time TIME,
    sprint_date DATE,
    sprint_time TIME
);
"""

# Ejecutar las consultas para crear las tablas
cursor.execute(create_drivers_table)
cursor.execute(create_laps_table)
cursor.execute(create_races_table)

# Confirmar la transacción
conn.commit()

# Cerrar el cursor y la conexión
cursor.close()

print("Las tablas se han creado exitosamente.")

Las tablas se han creado exitosamente.

# Inserción de datos

In [10]:
cursor = conn.cursor()

for index, row in df_race.iterrows():
    cursor.execute("""
        INSERT INTO Formula1_Races (
            raceId, year, round, circuitId, name, date, time, url,
            fp1_date, fp1_time, fp2_date, fp2_time,
            fp3_date, fp3_time, quali_date, quali_time,
            sprint_date, sprint_time
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s,
            %s, %s, %s, %s,
            %s, %s
        )
        ON CONFLICT (raceId) DO UPDATE SET
            year = EXCLUDED.year,
            round = EXCLUDED.round,
            circuitId = EXCLUDED.circuitId,
            name = EXCLUDED.name,
            date = EXCLUDED.date,
            time = EXCLUDED.time,
            url = EXCLUDED.url,
            fp1_date = EXCLUDED.fp1_date,
            fp1_time = EXCLUDED.fp1_time,
            fp2_date = EXCLUDED.fp2_date,
            fp2_time = EXCLUDED.fp2_time,
            fp3_date = EXCLUDED.fp3_date,
            fp3_time = EXCLUDED.fp3_time,
            quali_date = EXCLUDED.quali_date,
            quali_time = EXCLUDED.quali_time,
            sprint_date = EXCLUDED.sprint_date,
            sprint_time = EXCLUDED.sprint_time;
    """, (
       row['raceId'], row['year'], row['round'], row['circuitId'], row['name'], 
        row['date'], row.get('time'), row.get('url'), row.get('fp1_date'), 
        row.get('fp1_time'), row.get('fp2_date'), row.get('fp2_time'),
        row.get('fp3_date'), row.get('fp3_time'), row.get('quali_date'),
        row.get('quali_time'), row.get('sprint_date'), row.get('sprint_time')
    ))
conn.commit()

    
for index, row in df_drivers.iterrows():
    cursor.execute("""
        INSERT INTO Formula1_Drivers (
            driverId, driverRef, number, code, forename, surname, dob, nationality, url
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s
        )
        ON CONFLICT (driverId) DO UPDATE SET
            driverRef = EXCLUDED.driverRef,
            number = EXCLUDED.number,
            code = EXCLUDED.code,
            forename = EXCLUDED.forename,
            surname = EXCLUDED.surname,
            dob = EXCLUDED.dob,
            nationality = EXCLUDED.nationality,
            url = EXCLUDED.url;
    """, (
        row['driverId'], row['driverRef'], row['number'], row.get('code'),
        row['forename'], row['surname'], row['dob'], row['nationality'], row.get('url')
    ))

# Confirmar la transacción
conn.commit()

for index, row in df_laps.iterrows():
    cursor.execute("""
        INSERT INTO Formula1_Laps (
            raceId, driverId, lap, position, time, milliseconds
        ) VALUES (
            %s, %s, %s, %s, %s, %s
        )
        ON CONFLICT (raceId, driverId, lap) DO UPDATE SET
            position = EXCLUDED.position,
            time = EXCLUDED.time,
            milliseconds = EXCLUDED.milliseconds;
    """, (
        row['raceId'], row['driverId'], row['lap'], row.get('position'),
        row.get('time'), row.get('milliseconds')
    ))

# Confirmar la transacción
conn.commit()


# Cerrar el cursor y la conexión
cursor.close()

# DUMP

In [11]:
import psycopg2
import pandas as pd

# Conexión a la base de datos

# Crear un cursor para ejecutar comandos SQL
cursor = conn.cursor()

# Función para exportar una tabla a CSV
def export_table_to_csv(table_name, output_file):
    query = f"SELECT * FROM {table_name};"
    cursor.execute(query)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]  # Obtener nombres de columnas

    # Crear un DataFrame de pandas
    df = pd.DataFrame(rows, columns=columns)

    # Exportar a CSV
    df.to_csv(output_file, index=False)

# Exportar las tablas deseadas
export_table_to_csv("Formula1_Drivers", "Formula1_Drivers.csv")
export_table_to_csv("Formula1_Laps", "Formula1_Laps.csv")
export_table_to_csv("Formula1_Races", "Formula1_Races.csv")

# Cerrar cursor y conexión
cursor.close()

print("Exportación de tablas completada.")

Exportación de tablas completada.

In [12]:
cursor = conn.cursor()

# Consulta SQL para obtener todos los registros de la tabla Formula1_Drivers
query = "SELECT * FROM Formula1_Drivers;"

# Ejecutar la consulta
cursor.execute(query)

# Obtener todos los resultados
rows = cursor.fetchall()

# Crear un DataFrame de pandas con los resultados
df_drivers_query = pd.DataFrame(rows, columns=[desc[0] for desc in cursor.description])
display(df_drivers_query)
# Cerrar el cursor y la conexión
cursor.close()
conn.close()

,driverid,code,givenname,familyname,dateofbirth,nationality,url
0,abate,NaN,Carlo,Abate,1932-07-10,Italian,http://en.wikipedia.org/wiki/Carlo_Mario_Abate
1,abecassis,NaN,George,Abecassis,1913-03-21,British,http://en.wikipedia.org/wiki/George_Abecassis
2,acheson,NaN,Kenny,Acheson,1957-11-27,British,http://en.wikipedia.org/wiki/Kenny_Acheson
3,adams,NaN,Philippe,Adams,1969-11-19,Belgian,http://en.wikipedia.org/wiki/Philippe_Adams
4,ader,NaN,Walt,Ader,1913-12-15,American,http://en.wikipedia.org/wiki/Walt_Ader
5,adolff,NaN,Kurt,Adolff,1921-11-05,German,http://en.wikipedia.org/wiki/Kurt_Adolff
6,agabashian,NaN,Fred,Agabashian,1913-08-21,American,http://en.wikipedia.org/wiki/Fred_Agabashian
7,ahrens,NaN,Kurt,Ahrens,1940-04-19,German,"http://en.wikipedia.org/wiki/Kurt_Ahrens,_Jr."
8,aitken,AIT,Jack,Aitken,1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken
9,albers,ALB,Christijan,Albers,1979-04-16,Dutch,http://en.wikipedia.org/wiki/Christijan_Albers
10,albon,ALB,Alexander,Albon,1996-03-23,Thai,http://en.wikipedia.org/wiki/Alexander_Albon
11,alboreto,NaN,Michele,Alboreto,1956-12-23,Italian,http://en.wikipedia.org/wiki/Michele_Alboreto
12,alesi,NaN,Jean,Alesi,1964-06-11,French,http://en.wikipedia.org/wiki/Jean_Alesi
13,alguersuari,ALG,Jaime,Alguersuari,1990-03-23,Spanish,http://en.wikipedia.org/wiki/Jaime_Alguersuari
14,alliot,NaN,Philippe,Alliot,1954-07-27,French,http://en.wikipedia.org/wiki/Philippe_Alliot
15,allison,NaN,Cliff,Allison,1932-02-08,British,http://en.wikipedia.org/wiki/Cliff_Allison
16,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
17,amati,NaN,Giovanna,Amati,1959-07-20,Italian,http://en.wikipedia.org/wiki/Giovanna_Amati
18,george_amick,NaN,George,Amick,1924-10-24,American,http://en.wikipedia.org/wiki/George_Amick
19,amick,NaN,Red,Amick,1929-01-19,American,http://en.wikipedia.org/wiki/Red_Amick
20,amon,NaN,Chris,Amon,1943-07-20,New Zealander,http://en.wikipedia.org/wiki/Chris_Amon
21,anderson,NaN,Bob,Anderson,1931-05-19,British,http://en.wikipedia.org/wiki/Bob_Anderson_(rac...
22,andersson,NaN,Conny,Andersson,1939-12-28,Swedish,http://en.wikipedia.org/wiki/Conny_Andersson_(...
23,mario_andretti,NaN,Mario,Andretti,1940-02-28,American,http://en.wikipedia.org/wiki/Mario_Andretti
24,andretti,NaN,Michael,Andretti,1962-10-05,American,http://en.wikipedia.org/wiki/Michael_Andretti
25,andrews,NaN,Keith,Andrews,1920-06-15,American,http://en.wikipedia.org/wiki/Keith_Andrews_(dr...
26,apicella,NaN,Marco,Apicella,1965-10-07,Italian,http://en.wikipedia.org/wiki/Marco_Apicella
27,armi,NaN,Frank,Armi,1918-10-12,American,http://en.wikipedia.org/wiki/Frank_Armi
28,arnold,NaN,Chuck,Arnold,1926-05-30,American,http://en.wikipedia.org/wiki/Chuck_Arnold
29,arnoux,NaN,René,Arnoux,1948-07-04,French,http://en.wikipedia.org/wiki/Ren%C3%A9_Arnoux