# Instalacion de Librerias

In [ ]:
!pip install transformers datasets
!pip install 'transformers[torch]'
!pip install psycopg2-binary
!pip install mysql-connector-python

# Carga de Librerias

In [1]:
import requests, csv, os ,warnings
import pandas as pd
from datetime import date
import json
import shutil
import requests

In [2]:
warnings.filterwarnings("ignore")

# Creacion del listado de URL para APIREST

In [3]:
urlBase="https://api.jolpi.ca/ergast/f1"

In [4]:
# def get_data_from_api(endpoint, table_key_1, table_key_2):
#     try:
#         response = requests.get(f"{urlBase}/{endpoint}", params={"limit": 1000})
#         # Verifica si la solicitud fue exitosa (código de estado 200)
#         if response.status_code == 200:
#             # Convierte la respuesta JSON en un diccionario
#             data = response.json()
#             data = data['MRData']
#             print(data)
#             # Extrae los datos de la clave específica (e.g., 'DriverTable', 'RaceTable')
#             if table_key_1 in data:
#                 table_data = data[table_key_1][table_key_2]
#                 # Convierte la tabla en un DataFrame de pandas
#                 df = pd.DataFrame(table_data)
#                 print(f"Datos obtenidos de {endpoint} exitosamente.")
#                 return df
#             else:
#                 print(f"La clave '{table_key_1}' no se encontró en la respuesta.")
#                 return pd.DataFrame()  # Retorna un DataFrame vacío si no se encuentra la clave
#         else:
#             print(f"Error {response.status_code} al obtener datos de {endpoint}.")
#             return pd.DataFrame()  # Retorna un DataFrame vacío en caso de error
#     except Exception as e:
#         print(f"Error al conectar con la API: {e}")
#         return pd.DataFrame()

In [5]:
df_race = pd.read_csv("data/structured/races.csv")
# df_drivers = get_data_from_api("drivers", "DriverTable", "Drivers")
df_drivers = pd.read_csv("data/structured/drivers.csv")
# lee el csv data/structured/lap_times.csv
df_laps = pd.read_csv('data/structured/lap_times.csv')
# Muestra un resumen de los DataFrames obtenidos
print("Resumen de la tabla 'race':")
display(df_race)

print("\nResumen de la tabla 'drivers':")
display(df_drivers)

print("\nResumen de la tabla 'laps':")
display(df_laps)

Resumen de la tabla 'race':

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

Resumen de la tabla 'drivers':

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
855,857,piastri,81,PIA,Oscar,Piastri,2001-04-06,Australian,http://en.wikipedia.org/wiki/Oscar_Piastri
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,40,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto

Resumen de la tabla 'laps':

        raceId  driverId  lap  position      time  milliseconds
0          841        20    1         1  1:38.109         98109
1          841        20    2         1  1:33.006         93006
2          841        20    3         1  1:32.713         92713
3          841        20    4         1  1:32.803         92803
4          841        20    5         1  1:32.342         92342
...        ...       ...  ...       ...       ...           ...
582762    1138       855   57        15  1:37.875         97875
582763    1138       855   58        15  1:37.758         97758
582764    1138       855   59        15  1:37.759         97759
582765    1138       855   60        15  1:39.830         99830
582766    1138       855   61        15  1:38.975         98975

[582767 rows x 6 columns]

In [6]:
# Cambiar la columna 'time' en df_race a 'race_time'
df_race = df_race.rename(columns={"time": "race_time"})

# Cambiar la columna 'time' en df_laps a 'lap_time'
df_laps = df_laps.rename(columns={"time": "lap_time"})

# Reemplazar los valores '\\N' por None en los tres DataFrames
df_race = df_race.replace('\\N', None)
df_drivers = df_drivers.replace('\\N', None)
df_laps = df_laps.replace('\\N', None)


print("Resumen de la tabla 'race':")
display(df_race)

print("\nResumen de la tabla 'drivers':")
display(df_drivers)

print("\nResumen de la tabla 'laps':")
display(df_laps)

Resumen de la tabla 'race':

,raceId,year,round,circuitId,name,date,race_time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,None,None,None,None,None,None,None,None,None,None
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,None,None,None,None,None,None,None,None,None,None
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,None,None,None,None,None,None,None,None,None,None
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,None,None,None,None,None,None,None,None,None,None
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,None,None
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,None,None,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,None,None
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,None,None,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,None,None

Resumen de la tabla 'drivers':

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,None,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,None,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
855,857,piastri,81,PIA,Oscar,Piastri,2001-04-06,Australian,http://en.wikipedia.org/wiki/Oscar_Piastri
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,40,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto

Resumen de la tabla 'laps':

        raceId  driverId  lap  position  lap_time  milliseconds
0          841        20    1         1  1:38.109         98109
1          841        20    2         1  1:33.006         93006
2          841        20    3         1  1:32.713         92713
3          841        20    4         1  1:32.803         92803
4          841        20    5         1  1:32.342         92342
...        ...       ...  ...       ...       ...           ...
582762    1138       855   57        15  1:37.875         97875
582763    1138       855   58        15  1:37.758         97758
582764    1138       855   59        15  1:37.759         97759
582765    1138       855   60        15  1:39.830         99830
582766    1138       855   61        15  1:38.975         98975

[582767 rows x 6 columns]

# Preparo la BD

In [7]:
df_drivers.head(1)

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton

create database metastore_db;

CREATE TABLE Formula1_Drivers (
    driverId INTEGER PRIMARY KEY,
    driverRef TEXT NOT NULL,
    number INTEGER,
    code TEXT,
    forename TEXT NOT NULL,
    surname TEXT NOT NULL,
    dob DATE NOT NULL,
    nationality TEXT NOT NULL,
    url TEXT
);


CREATE TABLE Formula1_Laps (
    raceId INTEGER,
    driverId INTEGER,
    lap INTEGER,
    position INTEGER,
    time TEXT,
    milliseconds INTEGER,
    PRIMARY KEY (raceId, driverId, lap)
);


CREATE TABLE Formula1_Races (
    raceId INTEGER PRIMARY KEY,
    year INTEGER NOT NULL,
    round INTEGER NOT NULL,
    circuitId TEXT NOT NULL,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME,
    url TEXT,
    fp1_date DATE,
    fp1_time TIME,
    fp2_date DATE,
    fp2_time TIME,
    fp3_date DATE,
    fp3_time TIME,
    quali_date DATE,
    quali_time TIME,
    sprint_date DATE,
    sprint_time TIME
);

# Conexion a MariaDB

In [8]:
import mysql.connector
from mysql.connector import errorcode

# Conexión a la base de datos MariaDB
connMariaDB = mysql.connector.connect(
host='hive4-mariadb', # Cambia a tu host si es diferente
user='my_user', # Cambia por tu usuario
password='my_password', # Cambia por tu contraseña
database='my_mariadb_db' # Cambia por tu nombre de base de datos
)

# Conexion a PostgresDB

In [9]:
import psycopg2
conn = psycopg2.connect(
    dbname='metastore_db',  # Cambia por tu nombre de base de datos
    user='hive',        # Cambia por tu usuario
    password='password',  # Cambia por tu contraseña
    host='hive4-postgres',         # Cambia si es necesario
    port='5432'               # Cambia si es necesario
)

# Creación de tablas

In [10]:

cursor = conn.cursor()
cursor_mariadb = connMariaDB.cursor()
# Consultas para eliminar las tablas si existen
drop_drivers_table = "DROP TABLE IF EXISTS Formula1_Drivers;"
drop_laps_table = "DROP TABLE IF EXISTS Formula1_Laps;"
drop_races_table = "DROP TABLE IF EXISTS Formula1_Races;"

# Ejecutar las consultas para eliminar las tablas
cursor_mariadb.execute(drop_drivers_table)
cursor.execute(drop_laps_table)
cursor.execute(drop_races_table)

# Consultas para crear las tablas
create_drivers_table = """
    CREATE TABLE Formula1_Drivers (
    driverId INT PRIMARY KEY,
    driverRef VARCHAR(255) NOT NULL,
    number INT,
    code VARCHAR(10),
    forename VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    dob DATE NOT NULL,
    nationality VARCHAR(255) NOT NULL,
    url VARCHAR(500)
    );
"""

create_laps_table = """
CREATE TABLE IF NOT EXISTS Formula1_Laps (
    raceId INTEGER,
    driverId TEXT,
    lap INTEGER,
    position INTEGER,
    lap_time TIME,
    milliseconds INTEGER,
    PRIMARY KEY (raceId, driverId, lap)
);
"""

create_races_table = """
CREATE TABLE IF NOT EXISTS Formula1_Races (
    raceId INTEGER PRIMARY KEY,
    year INTEGER NOT NULL,
    round INTEGER NOT NULL,
    circuitId TEXT NOT NULL,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    race_time TIME,
    url TEXT,
    fp1_date DATE,
    fp1_time TIME,
    fp2_date DATE,
    fp2_time TIME,
    fp3_date DATE,
    fp3_time TIME,
    quali_date DATE,
    quali_time TIME,
    sprint_date DATE,
    sprint_time TIME
);
"""

# Ejecutar las consultas para crear las tablas
cursor_mariadb.execute(create_drivers_table)
cursor.execute(create_laps_table)
cursor.execute(create_races_table)

# Confirmar la transacción
conn.commit()
connMariaDB.commit()



print("Las tablas se han creado exitosamente.")

Las tablas se han creado exitosamente.

# Inserción de datos

In [11]:

for index, row in df_race.iterrows():
    cursor.execute("""
        INSERT INTO Formula1_Races (
            raceId, year, round, circuitId, name, date, race_time, url,
            fp1_date, fp1_time, fp2_date, fp2_time,
            fp3_date, fp3_time, quali_date, quali_time,
            sprint_date, sprint_time
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s,
            %s, %s, %s, %s,
            %s, %s
        )
        ON CONFLICT (raceId) DO UPDATE SET
            year = EXCLUDED.year,
            round = EXCLUDED.round,
            circuitId = EXCLUDED.circuitId,
            name = EXCLUDED.name,
            date = EXCLUDED.date,
            race_time = EXCLUDED.race_time,
            url = EXCLUDED.url,
            fp1_date = EXCLUDED.fp1_date,
            fp1_time = EXCLUDED.fp1_time,
            fp2_date = EXCLUDED.fp2_date,
            fp2_time = EXCLUDED.fp2_time,
            fp3_date = EXCLUDED.fp3_date,
            fp3_time = EXCLUDED.fp3_time,
            quali_date = EXCLUDED.quali_date,
            quali_time = EXCLUDED.quali_time,
            sprint_date = EXCLUDED.sprint_date,
            sprint_time = EXCLUDED.sprint_time;
    """, (
       row['raceId'], row['year'], row['round'], row['circuitId'], row['name'], 
        row['date'], row.get('race_time'), row.get('url'), row.get('fp1_date'), 
        row.get('fp1_time'), row.get('fp2_date'), row.get('fp2_time'),
        row.get('fp3_date'), row.get('fp3_time'), row.get('quali_date'),
        row.get('quali_time'), row.get('sprint_date'), row.get('sprint_time')
    ))
conn.commit()

    
for index, row in df_drivers.iterrows():
    cursor_mariadb.execute("""
       INSERT INTO Formula1_Drivers (
        driverId, driverRef, number, code, forename, surname, dob, nationality, url
        ) VALUES (
        %s, %s, %s, %s, %s, %s, %s, %s, %s
        )
        ON DUPLICATE KEY UPDATE
        driverRef = VALUES(driverRef),
        number = VALUES(number),
        code = VALUES(code),
        forename = VALUES(forename),
        surname = VALUES(surname),
        dob = VALUES(dob),
        nationality = VALUES(nationality),
        url = VALUES(url);
        """, (
        row['driverId'], row['driverRef'], row['number'], row.get('code'),
        row['forename'], row['surname'], row['dob'], row['nationality'], row.get('url')
        ))

# Confirmar la transacción
connMariaDB.commit()

for index, row in df_laps.iterrows():
    cursor.execute("""
        INSERT INTO Formula1_Laps (
            raceId, driverId, lap, position, lap_time, milliseconds
        ) VALUES (
            %s, %s, %s, %s, %s, %s
        )
        ON CONFLICT (raceId, driverId, lap) DO UPDATE SET
            position = EXCLUDED.position,
            lap_time = EXCLUDED.lap_time,
            milliseconds = EXCLUDED.milliseconds;
    """, (
        row['raceId'], row['driverId'], row['lap'], row.get('position'),
        row.get('lap_time'), row.get('milliseconds')
    ))

# Confirmar la transacción
conn.commit()


# Cerrar el cursor y la conexión
cursor.close()
cursor_mariadb.close()

True

# Queries

In [ ]:
import psycopg2
import pandas as pd

# Conexión a la base de datos

# Crear un cursor para ejecutar comandos SQL
cursor = conn.cursor()

# Función para exportar una tabla a CSV
def export_table_to_csv(table_name, output_file):
    query = f"SELECT * FROM {table_name};"
    cursor.execute(query)
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]  # Obtener nombres de columnas

    # Crear un DataFrame de pandas
    df = pd.DataFrame(rows, columns=columns)

    # Exportar a CSV
    df.to_csv(output_file, index=False)

# Exportar las tablas deseadas
export_table_to_csv("Formula1_Drivers", "Formula1_Drivers.csv")
export_table_to_csv("Formula1_Laps", "Formula1_Laps.csv")
export_table_to_csv("Formula1_Races", "Formula1_Races.csv")

# Cerrar cursor y conexión
cursor.close()

print("Exportación de tablas completada.")

In [12]:
cursor = conn.cursor()

# Consulta SQL para obtener todos los registros de la tabla Formula1_Drivers
query = "SELECT * FROM Formula1_Races;"

# Ejecutar la consulta
cursor.execute(query)

# Obtener todos los resultados
rows = cursor.fetchall()

# Crear un DataFrame de pandas con los resultados
df_drivers_query = pd.DataFrame(rows, columns=[desc[0] for desc in cursor.description])
display(df_drivers_query)
# Cerrar el cursor y la conexión
cursor.close()

,raceid,year,round,circuitid,name,date,race_time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,None,None,None,None,None,None,None,None,None,None
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,None,None,None,None,None,None,None,None,None,None
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,None,None,None,None,None,None,None,None,None,None
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,None,None,None,None,None,None,None,None,None,None
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,None,None
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,None,None,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,None,None
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,None,None,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,None,None

In [ ]:
conn.close()
connMariaDB.close()